### ISSUE TITLE
PropertyFieldCollectionData: Validation does not disable Save button

### ISSUE THREAD

**Issue by giveitaGo** [pnp/sp-dev-fx-property-controls#174]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
1.14.1

#### Expected / Desired Behavior / Question
When filling out a new record with required fields, the Save button should be disabled if form validation fails. 

#### Observed Behavior
If you are entering data for the first entry, the Save button is always active, even if form validation is failing. If you partially fill out a record and miss fields that are required, you can click the Save button, and the user is never alerted that the data was not saved.

If you have more than one record in the collection, the Save button remains active, despite errors on the most recent record. However, the Save button will disable when fields from previous records are no longer valid.

#### Steps to Reproduce
- Add CollectionData control to web part property pane
- Add Multiple string fields that are required
- Enter data for a new record, but leave one required field blank 

#### Recommendation
- When for validation fails on the new record, disable the Save button
OR
- Alert the user that the new record will not be saved, due to invalid data

**Comment by estruyf** [comment]
@giveitaGo I think you are referring to the following situation:

![Screenshot 2019-07-09 10 04 48](https://user-images.githubusercontent.com/2900833/60870407-13c0a400-a231-11e9-8c5b-c121bafb06e8.png)

In this case, the save button is active, because of the first line which will be saved. The new line will be ignored because that one is invalid. Once the first line is valid, it should show the following:

![Screenshot 2019-07-09 10 04 56](https://user-images.githubusercontent.com/2900833/60870486-423e7f00-a231-11e9-9ef0-99678d04994c.png)

Save button is remained active because otherwise, you cannot do changes to previously inserted records.

**Comment by giveitaGo** [comment]
@estruyf - That is a valid scenario, but so is simply adding a new record without editing the original record. Perhaps the "Save Button" shouldn't activate if the previous record(s) have not been modified and the new record is invalid. It's pretty confusing to show "Save" when the only data you've entered is invalid.

**Comment by AJIXuMuK** [comment]
In the current implementations it is a by design behavior.

Enabled button with`saveBtnLabel` text means that you will save changes to the existing items. If there are errors in these existing items, the button will be disabled.
If new added item is valid, the button text will be `saveAndAddBtnLabel`.
