### ISSUE TITLE
German localization broken

### ISSUE THREAD

**Issue by otze** [pnp/sp-dev-fx-property-controls#311]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 2.1.0        ]

#### Expected / Desired Behavior / Question
When testing a webpart that leverages PropertyFieldSwatchColorPicker the property is not showing with "gulp serve --locale=de-de"

#### Observed Behavior
It seems that line 1 of node_modules/@pnp/spfx-property-controls/lib/loc/de-de.js : 
>> declare var define: any;
is causing the issue. Propably it shouldn't be there at all...

#### Steps to Reproduce
see above

**Comment by mvdungen** [comment]
Same for the dutch nl-nl localization file. The `declare var define...` first code line is causing an error. By removing that line in the nl-nl.js file, the problem was solved. Looked at some other localization files, but not all are affected: `no.js` is fine, but `nb-no.js` or `fr-fr.js` are broken. Fixed it for now by removing the first line.

**Comment by AJIXuMuK** [comment]
Thank you @otze for reporting that!
And thank you @mvdungen for checking other localizations.

The fix has been done and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/).
